### ISSUE TITLE
Can't open tweet details

### ISSUE THREAD

**Issue by eugenioperea** [dangeredwolf/ModernDeck#250]
I can't open tweet details, or even open a tweet to see what it's responding to. If I click on a tweet, nothing happens. If I try to right-click, I get this
![Screenshot from 2022-04-10 16-04-23](https://user-images.githubusercontent.com/84279757/162639865-34a4758f-f096-4278-8879-fb19c544c1e0.png)
![Screenshot from 2022-04-10 16-04-41](https://user-images.githubusercontent.com/84279757/162639868-1ec56f77-aa41-4948-8248-7d4ab52d1e40.png)
:

Am I doing something wrong?

**Comment by dangeredwolf** [comment]
Left clicking on a tweet should show the tweet details, is that not happening? Are you on the latest version of ModernDeck (currently 9.4.1)?

**Comment by eugenioperea** [comment]
That is not happening, no. When I left-click, nothing happens. I even moved to the Beta channel, to see if that helped, so I'm on 9.5. This is on Ubuntu Linux 21.10.

**Comment by dangeredwolf** [comment]
Is this the webpack or AppImage version?

**Comment by dangeredwolf** [comment]
Is this the Flatpak or AppImage version?

**Comment by eugenioperea** [comment]
AppImage. I have no problem switching, if you say so.

**Comment by dangeredwolf** [comment]
It shouldn't make a difference if you're on AppImage, I was wondering if you were on the Flatpak version because its sandboxing has caused some bugs in the past.

I released version 9.4.4 just yesterday which has an upgraded version of Electron to fix other bugs, can you try and see if it still happens on that version?

**Comment by eugenioperea** [comment]
It works! Version10.0 Beta (build 1869) and left-click works correctly. Thank you for your response and for such a great piece of software.

**Comment by eugenioperea** [comment]
The issue is back with 10.0 Beta 1984 (literally 1984!)

**Comment by dangeredwolf** [comment]
Hey, sorry for lack of response before, as I mentioned in DMs it’s finals season and I’m in college so I’ve been a lot busier now than usual.

i believe I upgraded Electron in build 1984 (I’m glad you also think it’s funny that I stopped on that number LOL) and I wonder if they reintroduced a bug in it because if it was working fine in the last build. I’d love to submit a bug upstream but I haven’t been able to reproduce it. 

To help me reproduce it, if you would copy your settings from diagnostics that might prove useful (Go to Settings > About and click the ModernDeck logo 5 times to get to it).(Come to think of it I’ve been meaning to add a simple Copy button to the dialog but I haven’t yet, oops, been on the backburner for 10.0)

**Comment by eugenioperea** [comment]
Thanks for responding!

Diagnostics

ModernDeck 10.0.0 (Build 1984)
Built 2022-04-27T08:07:34.833Z

Platform: Electron
OS: Linux
Architecture: amd64

TD.buildID: 884517077f738679775f7cd128e7f53cb0e6aa5c
TD.version: 4.0.220504185111
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) ModernDeck/10.0.0-beta-1984 Chrome/100.0.4896.127 Electron/18.1.0 Safari/537.36

Loaded extensions:
dark.css, darker.css, blue.css, fixedarrows.css, threadIndicator.css, altsensitive.css, scrollbarsnarrow.css, newcharacterindicator.css

User preferences:
mtd_theme: darker
mtd_color_theme: blue
mtd_selectedfont: Roboto
mtd_customcss: [not set]
mtd_headposition: classic
mtd_usefixedarrows: true
mtd_nonewtweetsbutton: true
mtd_noemojipicker: true
mtd_modalKeepOpen: true
mtd_hideMessages: [not set]
mtd_threadIndicator: true
mtd_sensitive_alt: true
mtd_scrollbar_style: scrollbarsnarrow
mtd_columnwidth: 300
mtd_fontsize: 100
mtd_avatarsize: 48
mtd_round_avatars: true
mtd_newcharindicator: true
mtd_nocontextmenuicons: true
mtd_column_visibility: true
mtd_sounds: true
mtd_nftAvatarAction: nothing
mtd_nftDontBlockFollowing: true
mtd_nftNotify: true
mtd_outlines: true
mtd_highcontrast: [not set]
mtd_nativetitlebar: true
mtd_nativeEmoji: [not set]
mtd_nativecontextmenus: true
mtd_updatechannel: beta
mtd_systemtray: true
mtd_background: [not set]
mtd_inspectElement: [not set]
mtd_timeFormat: default
mtd_shortDateFormat: default
mtd_abbrevNumbers: true
mtd_collapsed_columns: 121,97,115,127,109,106,130,103,130,121,97,115,127,109,106,118,103
mtd_last_version: 10.0.0
mtd_replace_favicon: true
