### ISSUE TITLE
Proxy / Censor block access feature?

### ISSUE THREAD

**Issue by mbs0ft** [dangeredwolf/ModernDeck#300]
I'm from Russia, and Twitter is blocked by _Roskomnadzor_, and we don't have access without VPN.

If that possible, can ModernDock have in-build proxy settings (or something called FuckDPI) feature?

![image](https://user-images.githubusercontent.com/22106304/171875460-781e61d9-1d13-44a1-bf24-f538524a5ef6.png)

**Comment by dangeredwolf** [comment]
Hi, I actually already planned on adding proper support for proxies in ModernDeck 10, so I'll be working on this ASAP. I'll let you know whenever a build with proper proxy support is available.

**Comment by dangeredwolf** [comment]
Thanks for the suggestion, I've implemented this now and it'll show up in the next 10.0 beta.

I will note for when it is out that at the moment you need to go to Settings to configure this, but you need an active connection in order to enter settings. However, ModernDeck already respects the system proxy so if you set a whole-system proxy it will be able to launch and you can specify one just for ModernDeck and then change it back. At some point I might try to add proxy settings to the connection error screen, but this'll take a lot more effort.
![Screenshot 2022-06-12 at 20 56 11](https://user-images.githubusercontent.com/2636265/173263249-bf78c5f9-83be-49ba-a2c8-15240e71ace9.png)
You can use a list of proxy servers (http, https, socks4, socks5 all work) or a PAC script.
