### ISSUE TITLE
create poll in tweetdeck

### ISSUE THREAD

**Issue by ashkitten** [dangeredwolf/ModernDeck#82]
not sure if this is possible but you can try?

**Comment by ciolt** [comment]
I've tried. It's not possible (or at most, very very difficult) to intercept TweetDeck's functions that control the data that's sent to Twitter's API for posting a tweet.

At most, the Tweet box can be re-created using a custom function, but that'd be very complicated and require a lot of work. Another thing to try is to create a global listener that waits for network transfers and run a function every time something is sent (i.e. the request to post a Tweet). However, that would lag the browser _WAY_ too much and is very prone to break with a TweetDeck update (that happens sometimes).

Ask @eramdam if he has any plans to add polls to BetterTweetDeck, as this question is more relevant to the discussion of BTD than ModernDeck.

**Comment by eramdam** [comment]
> Ask @eramdam if he has any plans to add polls to Better TweetDeck, as this question is more relevant to the discussion of BTD than ModernDeck.

😁  I still have to checkout the way polls got implemented in ModernDeck. @dangeredwolf and I had a talk about it a few weeks ago and he told me he managed to get them working.

As for the creation of polls, since TweetDeck is somewhat acting like a 3rd party client (it's subject to rate limit like any other 3rd client) (yes that doesn't make any sense) I guess it would be a lot of work to actually trick the Twitter API into believing you're an official app.. Typically the kind of modification you don't even want to try when you don't actually work on TweetDeck itself.

**Comment by ciolt** [comment]
>he told me he managed to get them working.

Well if he "managed to get them working," then either:
1) [he hasn't pushed that to GitHub](https://github.com/dangeredwolf/ModernDeck/search?q=poll)
2) he partly lied because viewing polls it's already implemented in TweetDeck as part of an update (not sure because, you know, ^^number 1)

And also, after looking into Twitter's API docs, it's not possible to send a POST request to create a Tweet with a poll, they only come embedded into an API response for a Tweet status.

**Comment by eramdam** [comment]
1. Or maybe it wasn't @dangeredwolf talking w/ me on [this thread](https://twitter.com/ModernDeck/status/732666767567429632) ? 😅 

2. Omg indeed. Must be recent because at the time of that thread there was not a way to see polls in TD + I checked the data presented by TD back then and there was nothing about polls except the fact that tweets had them.
Now TweetDeck has more useful infos about polls so I could definitely do something :) 

![screen shot 2016-06-26 at 11 54 54 pm](https://cloud.githubusercontent.com/assets/1409924/16371145/78ac1cec-3bf9-11e6-8654-e69ea5f1b53f.png)

**Comment by ciolt** [comment]
You can collect the data from the polls in TweetDeck, but you can't post polls to Twitter.

This is because TweetDeck directly uses the [Twitter API](api.twitter.com) instead of its own endpoint (which should be the same one powering Twitter Web but it's not).

And Twitter's API seems to not have any plans of adding polls as a parameter for status updates.

**Comment by ciolt** [comment]
Now that I've looked at the thread, the implementation for the creation of polls would be very hacky. And insecure at that, too (force-rewriting the content-security headers on twitter.com may worry some users, and it'd be very shady to throw that under the rug without clear explanation).

**Comment by ashyon** [comment]
If you're trying to use twitter.com to hack in poll creation remember that
it only allows one user to log in at once so you're gonna have to figure a
workaround for that as well

**Comment by mmahgoub** [comment]
2016?!

**Comment by dangeredwolf** [comment]
@ciolt I got *rendering polls* within TweetDeck working back in the day, which is no longer necessary today, since TweetDeck can already do that. I still cannot find a practical way to *create* them.

Anyhow, as this thread is quite old, I'm going to go ahead and close it, but it might be worth revisiting, especially with this whole "new composer" thing.
